### ISSUE TITLE
False positives in urls

### ISSUE THREAD

**Issue by czikus** [textlint-rule/textlint-rule-en-capitalization#10]
The following sentence in a text file:

```
This is a sentence: https://google.com//search?q=something
                                               ^^^^^^^^^^^
```

generates:

```
 9  48 error    en-capitalization Paragraph: Follow the standard capitalization rules for American English.
 See https://owl.english.purdue.edu/owl/resource/592/01/ (textlint)
```

**Comment by azu** [comment]
Probably, the reason of this error come from sentence-splitter bug. https://github.com/azu/sentence-splitter/issues/22

**Comment by azu** [comment]
I can not reproduce it in markdown.
textlint's Markdown parser `https://google.com//search?q=something` as Link node and it will be ignored.

![image](https://user-images.githubusercontent.com/19714/113301232-c310a900-9339-11eb-8ad6-3446c5d3ddfb.png)

If the URL is written as plain text, it is an expected error.
If you want to avoid this error, you need to write the URL as `Link` node or `Code` node.

In markdown:

```
<https://google.com//search?q=something>
https://google.com//search?q=something // probably auto-linked
`https://google.com//search?q=something` // this is code
```


If I missed, please re-open this issue.
