### ISSUE TITLE
Complains about file names in text

### ISSUE THREAD

**Issue by sapegin** [textlint-rule/textlint-rule-en-capitalization#2]
Text:

```md
# Anatomy of a Package

A minimal npm package should contain metadata in a _package.json_ file and an associated source file (usually _index.js_). In practice, packages contain more than that and you will have at least a license file and the source in various formats.
```

Result:

```
   3:61   ✓ error  Heading: Follow the standard capitalization rules for American English.
See https://owl.english.purdue.edu/owl/resource/592/01/  en-capitalization
   3:118  ✓ error  Heading: Follow the standard capitalization rules for American English.
See https://owl.english.purdue.edu/owl/resource/592/01/  en-capitalization
```

Not sure it’s a bug or a feature ;-)

**Comment by azu** [comment]
It is a bug.
Fmm. This issue come from [sentence-splitter](https://github.com/azu/sentence-splitter "sentence-splitter"). `sentence-splitter` just split text by `.` 

```js
const source = new StringSource(node);
// Textlint Node to Plaing Text
const sourceText = source.toString();
// Split Plain text by `.`
const sentences = split(sourceText);
```
https://github.com/textlint-rule/textlint-rule-en-capitalization/blob/f07443b777b076366502f01a0d39742ecb79fb4c/src/textlint-rule-en-capitalization.js#L57-L59

As a result, it split `_package.json_` to `["package", "json"]` sentences.(This is wrong sentences)

We need to more conventional sentence-splitter for textlint nodes...
(Paragraph Node to Sentence Nodes.)

📝 Workaround resolution, fill `Emphasis` node's value with dummy value like `_package.json_` => `_XXXXXXXXX_`.

**Comment by sapegin** [comment]
> This issue come from sentence-splitter. sentence-splitter just split text by .

Shouldn’t it require non-alphabetic character after `.`?

**Comment by azu** [comment]
> Shouldn’t it require non-alphabetic character after .?

Yes. You're correct.
But, current [sentence-splitter](https://github.com/azu/sentence-splitter "sentence-splitter") implementation is buggy. 🐛

**Comment by azu** [comment]
I've completely rewrited sentence splitter.

- https://github.com/azu/sentence-splitter/releases/tag/3.0.0

And, I've upgraded this rule to use latest sentence-splitter #3 

- https://github.com/textlint-rule/textlint-rule-en-capitalization/releases/tag/2.0.0
