### ISSUE TITLE
Error `Cannot read property '0' of undefined` when a code block starts with blank spaces

### ISSUE THREAD

**Issue by amimas** [textlint-rule/textlint-rule-en-capitalization#4]
I am getting the following error when using this rule:

```text
✖ Error
Cannot read property '0' of undefined
at /Users/amimas/git-repo/docs/references.md

✖ Stack trace
TypeError: Cannot read property '0' of undefined
at /Users/amimas/git-repo/docs/references.md
    at new SourceCode (/Users/amimas/git-repo/website/node_modules/sentence-splitter/lib/parser/SourceCode.js:28:41)
    at new SplitParser (/Users/amimas/git-repo/website/node_modules/sentence-splitter/lib/sentence-splitter.js:31:23)
    at splitAST (/Users/amimas/git-repo/website/node_modules/sentence-splitter/lib/sentence-splitter.js:154:23)
    at checkNode (/Users/amimas/git-repo/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js:63:25)
    at /Users/amimas/git-repo/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js:157:13
    at Array.forEach (<anonymous>)
    at /Users/amimas/git-repo/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js:156:23
    at /Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/promise-event-emitter.js:26:36
    at Array.forEach (<anonymous>)
    at RuleTypeEmitter.PromiseEventEmitter.emit (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/promise-event-emitter.js:25:38)
    at Controller.enter (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/textlint-core-task.js:129:51)
    at Controller.__execute (/Users/amimas/git-repo/website/node_modules/@textlint/ast-traverse/lib/ast-traverse/src/index.js:45:31)
    at Controller.traverse (/Users/amimas/git-repo/website/node_modules/@textlint/ast-traverse/lib/ast-traverse/src/index.js:116:28)
    at TextLintCoreTask.startTraverser (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/textlint-core-task.js:124:28)
    at TextLintCoreTask.start (/Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/linter-task.js:34:14)
    at /Users/amimas/git-repo/website/node_modules/@textlint/kernel/lib/kernel/src/task/task-runner.js:26:18
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I was able to narrow down the root cause to the formatting of a particular markdown file. If I have the following content, textlint fails to run with this particular rule being enabled. If I don't use this rule, textlint runs successfully with all other rules configured.

Below is a sample of markdown file content where this rule breaks. Notice that the code block does not start at the beginning of the line.

![image](https://user-images.githubusercontent.com/16211767/56741963-dd9b7a00-6741-11e9-9fed-c0f7df72bf4e.png)

The reason for the code block to not start at the beginning of the line is because it is rendered by markdown parsers like this, where it properly appears as part of a list item.

![image](https://user-images.githubusercontent.com/16211767/56742042-06237400-6742-11e9-8dfa-c9a9235213b6.png)

If I remove the blank lines at the beginning of the code block in the markdown, it gets rendered like this. It does not look properly aligned. Furthermore, I have other rules enabled that will now complain that the last list item should be `1` instead of `3` because it appears as a completely separate list.

![image](https://user-images.githubusercontent.com/16211767/56742234-53074a80-6742-11e9-8b2b-2b02695ffa3a.png)

If I have a regular paragraph instead of the code block which also starts with blank spaces within the list items, there's no problem. It works perfectly fine. Looks like the issue happens only when code block is used in this manner.

Not sure if this is a complicated bug or not.

**Comment by amimas** [comment]
Could it be because of sentence-splitter? I noticed that currently this repo is using version 3.0.1 but version 3.0.11 is available already.

https://github.com/azu/sentence-splitter

Would upgrading this dependency fix this issue?

**Comment by azu** [comment]
I've confirmed.

textlint-rule-en-capitalization can not handle following text.

```
1. First text.

    ```bash
    ssh -i <key>
        -L <path>
        location@ip
    ```

```

It is problem of this rule, because this rule pass CodeBlock node as Paragraph node.
This usage of sentence-splitter is wrong.

https://github.com/textlint-rule/textlint-rule-en-capitalization/blob/e89d740c8302169f21c2c496179dadbceb706862/src/textlint-rule-en-capitalization.js#L148

AST: https://textlint.github.io/astexplorer/

```
{
  "type": "Document",
  "children": [
    {
      "type": "List",
      "ordered": true,
      "start": 1,
      "loose": true,
      "children": [
        {
          "type": "ListItem",
          "loose": true,
          "checked": null,
          "children": [
            {
              "type": "Paragraph",
              "children": [
                {
                  "type": "Str",
                  "value": "First text.",
                  "loc": {
                    "start": {
                      "line": 1,
                      "column": 3
                    },
                    "end": {
                      "line": 1,
                      "column": 14
                    }
                  },
                  "range": [
                    3,
                    14
                  ],
                  "raw": "First text."
                }
              ],
              "loc": {
                "start": {
                  "line": 1,
                  "column": 3
                },
                "end": {
                  "line": 1,
                  "column": 14
                }
              },
              "range": [
                3,
                14
              ],
              "raw": "First text."
            },
            {
              "type": "CodeBlock",
              "lang": "bash",
              "value": "ssh -i <key>\n    -L <path>\n    location@ip",
              "loc": {
                "start": {
                  "line": 3,
                  "column": 4
                },
                "end": {
                  "line": 7,
                  "column": 7
                }
              },
              "range": [
                20,
                90
              ],
              "raw": "```bash\n    ssh -i <key>\n        -L <path>\n        location@ip\n    ```"
            }
          ],
          "loc": {
            "start": {
              "line": 1,
              "column": 0
            },
            "end": {
              "line": 7,
              "column": 7
            }
          },
          "range": [
            0,
            90
          ],
          "raw": "1. First text.\n\n    ```bash\n    ssh -i <key>\n        -L <path>\n        location@ip\n    ```"
        }
      ],
      "loc": {
        "start": {
          "line": 1,
          "column": 0
        },
        "end": {
          "line": 7,
          "column": 7
        }
      },
      "range": [
        0,
        90
      ],
      "raw": "1. First text.\n\n    ```bash\n    ssh -i <key>\n        -L <path>\n        location@ip\n    ```"
    }
  ],
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 9,
      "column": 0
    }
  },
  "range": [
    0,
    92
  ],
  "raw": "1. First text.\n\n    ```bash\n    ssh -i <key>\n        -L <path>\n        location@ip\n    ```\n\n"
}
```

I'll fix it  as soon as.

**Comment by azu** [comment]
@amimas Thanks for report.
I've fixed it and release https://github.com/textlint-rule/textlint-rule-en-capitalization/releases/tag/2.0.2

**Comment by amimas** [comment]
Wow!! Thanks @azu for the quick fix. I will try it out soon. Thanks again.
