### ISSUE TITLE
Wrong warnings

### ISSUE THREAD

**Issue by Mister-Hope** [textlint-rule/textlint-rule-en-capitalization#7]
![image](https://user-images.githubusercontent.com/33315834/96370448-6e64e180-1190-11eb-995d-c0a460f64082.png)

Besides, I don't think I should write 19<sup>Th</sup> instead of 19<sup>th</sup>.

![image](https://user-images.githubusercontent.com/33315834/96370513-a79d5180-1190-11eb-95d2-83c993b62572.png)

I would like to consider first one as a bug(It don't contain english characters at all), and the second one as an enhance.

BTW: all of them is diplayed as `can be autofixed`, but none of them changes after I run with `--fix`

**Comment by azu** [comment]
Can you paste actual text as plain text?

**Comment by Mister-Hope** [comment]
```md
- 19^th^
```

Which is parsed by markdown-it-sup, and will display as:

- 19<sup>th</sup>

```md
8-) :) :\* :( :-) :-( ;)
```

should be 

😎 😃 😗 😦 😃 😦 😉

**Comment by Mister-Hope** [comment]
Infomation provided. Any progress on this issue?

**Comment by azu** [comment]
Thanks.

I confirmed. 

When you use the number-started text, you get wrong result.

Example
```
1st line.
```

**Comment by azu** [comment]
Fixed in https://github.com/textlint-rule/textlint-rule-en-capitalization/releases/tag/v2.0.3
